source 'https://rubygems.org'

gem 'test-kitchen'
gem 'chefspec'
gem 'berkshelf'
gem 'kitchen-ec2'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'drud', git: 'https://gitlab.com/harvard-atg/drud.git', branch: 'atg'
gem 'foodcritic'
gem 'rubocop'
gem 'guard'
gem 'guard-foodcritic'
gem 'guard-kitchen', github: 'trickyearlobe/guard-kitchen', branch: 'support_guard_2'
gem 'guard-rspec'
gem 'guard-rubocop'
